version: '2.2'

services:
        #### Elasticsearch Container Compose  #####    
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elastic
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node  
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"  
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana
    depends_on: 
    - es01
    ports:
      - 5601:5601
    environment:
      - XPACK_ENCRYPTION_KEY=${XPACK_ENCRYPTION_KEY}
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0

      - 'ELASTICSEARCH_HOSTS=["https://es01:9200"]'
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=sv0e4tSIYnQGF0gc1h6M
      - 'ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=["certs/ca/ca.crt"]'
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate

      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY=certs/kibana/kibana.key
      - SERVER_SSL_CERTIFICATE=certs/kibana/kibana.crt
      - 'SERVER_SSL_CERTIFICATEAUTHORITIES=["certs/ca/ca.crt"]'

      - xpack.security.enabled=true
      - XPACK_SECURITY_ENCRYPTIONKEY=${XPACK_ENCRYPTION_KEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${XPACK_ENCRYPTION_KEY}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${XPACK_ENCRYPTION_KEY}
    volumes: 
      - certs:/usr/share/kibana/config/certs
      - kibanadata01:/usr/share/kibana/data
      # - ./kibana/config/kibana.yml:${KIBANA_DIR}/config/kibana.yml:ro
volumes:
  certs:
    driver: local
  esdata01:
    driver: local
  kibanadata01:
    driver: local  