version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false  
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.1
    container_name: logstash
    volumes:
      - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro  
      - ./pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    ports:
      - "5044:5044"    
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1
    container_name: kibana
    depends_on:
      - elasticsearch  
    volumes:
      - kibanadata:/usr/share/kibana/data  
    ports:
      - "5601:5601"
    networks:
      - elk

volumes:
  esdata:
    driver: local
  kibanadata:
    driver: local 

networks:
  elk:
    driver: bridge
